GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/15

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Somtochukwu Jeremy",
    "subscribedToChannel": "Don Cash"
}

###
GET http://localhost:3000/subscribers/655672a896ec42437a43d45c

###
DELETE  http://localhost:3000/subscribers/655677f233a521f100772ebc

###
PATCH  http://localhost:3000/subscribers/6556726696ec42437a43d45a
